import { spin } from './spin.js';
import { bytesToHex } from './crypto.js';

let running = false;
let batchSize = 1000;

onmessage = async (e) => {
  const { cmd } = e.data;

  if (cmd === 'start') {
    if (running) return;
    running = true;

    while (running) {
      let winResult = null;
      let count = 0;
      let lastHex = '';

      // Run a batch of spins synchronously to maximize CPU utilization
      for (let i = 0; i < batchSize; i++) {
        const result = await spin();
        count++;
        lastHex = result.privKeyHex; // Use the hex generated by spin()

        if (result.win) {
          winResult = result;
          running = false;
          break;
        }
      }

      // Send the batch progress back to the main thread
      postMessage({
        type: 'batch_complete',
        count: count,
        winResult: winResult,
        lastHex: lastHex
      });

      // Yield to the event loop so the worker can receive 'stop' messages
      await new Promise(resolve => setTimeout(resolve, 0));
    }
  } else if (cmd === 'stop') {
    running = false;
  }
};
